name: 'Compile gRPC'
description: 'Compile gRPC for a given language'
inputs:
  language:  # id of input
    description: 'Programming language'
    required: true
  out_repo: 
    description: 'Repo to deploy to'
    required: true
  token:
    description: 'Token to allow pushing changes'
    required: true
  
runs:
  using: "composite"
  steps:
    - uses: whyakari/github-repo-action@v3.1
      with:
        owner: CraftyLlamaCoalition
        repository: ${{ inputs.out_repo }}
        access-token: ${{ inputs.token }}
        branch: main
        
    - name: Remove Old Code
      run: find ${{ inputs.out_repo }} -mindepth 1 -type d -not -path '*/.git*' -exec rm -rf {} +
      shell: bash

    - name: Move compiled gRPC
      run: cp -r generated/${{ inputs.language }}/* ${{ inputs.out_repo }}
      shell: bash
      
    - name: Commit and push changes
      run: |
        cd ${{ inputs.out_repo }}
        git config --global user.email "craftyllama.ai@gmail.com"
        git config --global user.name "That Crafty Llama"
        git add .
        git remote set-url origin https://$GITHUB_TOKEN@github.com/CraftyLlamaCoalition/${{ inputs.out_repo }}.git
        git config --list
        pwd
        git commit -m "Compile protobuf files"
        git push origin main # Replace branch-name with the desired branch
        cd ../
      env: 
         GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash

      
